- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: create roboshop system user
  ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    system: true
    home: /app
- name: download application
  ansible.builtin.unarchive:
    src: "https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v{{ app_version }}.zip"
    dest: /app
    remote_src: yes    

- name: "download {{ component }} code"
  ansible.builtin.get_url:
    url: "https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip"
    dest: /tmp/{{ component }}.zip


- name: install dependencies
  community.general.npm:
    path: /app

# this module thinks file exist on ansible control server, needs to extract on to remote machine
# remote_src: yes means files already exist in catalogue server
- name: "extract {{ component }} code"
  ansible.builtin.unarchive:
    src: "/tmp/{{ component }}.zip"
    dest: /app
    remote_src: yes

- name: restart {{ component }}
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted    